### ISSUE TITLE
compilation on ubuntu 18.04

### ISSUE THREAD

**Issue by thefuzzyorange** [martin31821/fusion-kbd-controller#2]
Hi Martin!

This is a great util and I've been looking for this for linux for sometime!

Have you had an success compiling this under Ubuntu 18.04. 
I tried following your instructions but I cannot get it right due issues with how lib-usb is resolved. I spent a few hours trying various options, but I have very little knowledge of gcc and how all the resolving works but I cant get past the below =(

`➜  gcc $(pkg-config --libs --cflags libusb-1.0) main.c
/tmp/ccan2wa3.o: In function `set_mode':
main.c:(.text+0xdb): undefined reference to `libusb_control_transfer'
main.c:(.text+0x16c): undefined reference to `libusb_control_transfer'
/tmp/ccan2wa3.o: In function `set_custom_mode':
main.c:(.text+0x230): undefined reference to `libusb_control_transfer'
main.c:(.text+0x2aa): undefined reference to `libusb_interrupt_transfer'
main.c:(.text+0x342): undefined reference to `libusb_control_transfer'
/tmp/ccan2wa3.o: In function `main':
main.c:(.text+0x3f0): undefined reference to `libusb_init'
main.c:(.text+0x43e): undefined reference to `libusb_open_device_with_vid_pid'
main.c:(.text+0x461): undefined reference to `libusb_exit'
main.c:(.text+0x47c): undefined reference to `libusb_set_auto_detach_kernel_driver'
main.c:(.text+0x4a2): undefined reference to `libusb_set_auto_detach_kernel_driver'
main.c:(.text+0x4c8): undefined reference to `libusb_claim_interface'
main.c:(.text+0x504): undefined reference to `libusb_claim_interface'
main.c:(.text+0x656): undefined reference to `libusb_release_interface'
main.c:(.text+0x667): undefined reference to `libusb_release_interface'
main.c:(.text+0x673): undefined reference to `libusb_close'
main.c:(.text+0x67f): undefined reference to `libusb_exit'
collect2: error: ld returned 1 exit status
`

**Comment by martin31821** [comment]
can you paste the output of `pkg-config --libs --cflags libusb-1.0` ? 
It seems like it can't find the libusb library...

**Comment by thefuzzyorange** [comment]
Here you go

`
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
`

**Comment by martin31821** [comment]
Please install `libusb-1.0-0-dev` and try again

**Comment by thefuzzyorange** [comment]
So I have upgraded to 18.10 since last post and have tried compiling on that. 

First thing to note, there is no libusb-1.0 available in ubuntu repo when trying to install via sudo apt install. There are only the following packages
libusb-1.0-0
libusb-1.0-0-dev
libusb-1.0-doc

Having installed that running 
pkg-config --list-all | grep usb results in 
usbutils                       usbutils - USB device database
libusb                         libusb - USB access library

Running : gcc $(pkg-config --libs --cflags libusb-1.0) main.c

Results in:

Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
main.c:7:10: fatal error: libusb-1.0/libusb.h: No such file or directory
 #include <libusb-1.0/libusb.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Running : gcc $(pkg-config --libs --cflags libusb) main.c   

Results In 

main.c:7:10: fatal error: libusb-1.0/libusb.h: No such file or directory
 #include <libusb-1.0/libusb.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Does that help with anything?

**Comment by thefuzzyorange** [comment]
Install libusb-1.0-0.dev and the result below 

gcc $(pkg-config --libs --cflags libusb-1.0) main.c
/usr/bin/ld: /tmp/ccxDKnu9.o: in function `set_mode':
main.c:(.text+0xe1): undefined reference to `libusb_control_transfer'
/usr/bin/ld: main.c:(.text+0x172): undefined reference to `libusb_control_transfer'
/usr/bin/ld: /tmp/ccxDKnu9.o: in function `set_custom_mode':
main.c:(.text+0x236): undefined reference to `libusb_control_transfer'
/usr/bin/ld: main.c:(.text+0x2b0): undefined reference to `libusb_interrupt_transfer'
/usr/bin/ld: main.c:(.text+0x348): undefined reference to `libusb_control_transfer'
/usr/bin/ld: /tmp/ccxDKnu9.o: in function `main':
main.c:(.text+0x3f6): undefined reference to `libusb_init'
/usr/bin/ld: main.c:(.text+0x444): undefined reference to `libusb_open_device_with_vid_pid'
/usr/bin/ld: main.c:(.text+0x467): undefined reference to `libusb_exit'
/usr/bin/ld: main.c:(.text+0x482): undefined reference to `libusb_set_auto_detach_kernel_driver'
/usr/bin/ld: main.c:(.text+0x4a8): undefined reference to `libusb_set_auto_detach_kernel_driver'
/usr/bin/ld: main.c:(.text+0x4ce): undefined reference to `libusb_claim_interface'
/usr/bin/ld: main.c:(.text+0x50a): undefined reference to `libusb_claim_interface'
/usr/bin/ld: main.c:(.text+0x65c): undefined reference to `libusb_release_interface'
/usr/bin/ld: main.c:(.text+0x66d): undefined reference to `libusb_release_interface'
/usr/bin/ld: main.c:(.text+0x679): undefined reference to `libusb_close'
/usr/bin/ld: main.c:(.text+0x685): undefined reference to `libusb_exit'

**Comment by martin31821** [comment]
That's strange, it seems pkg-config couldn't find libusb, I couldn't reproduce this in a virtual machine.
Can you try to bypass pkg-config by using `gcc -lusb-1.0 main.c`?
According to the ubuntu package mirror, the library should be found automatically.

**Comment by thefuzzyorange** [comment]
Running gcc -lusb-1.0 main.c results in eact same error as previous run 
gcc $(pkg-config --libs --cflags libusb-1.0) main.c.

You say you managed to compile a binary for 18.10 inside a VM? Is it possible to get the binary to test if it works on my laptop?

**Comment by martin31821** [comment]
Figured out the problem:
you need to use `gcc main.c $(pkg-config --libs --cflags libusb-1.0)` (specify `main.c` before `-l` and `-I` flags, because gcc argument order is relevant).

Please close if it works for you.

**Comment by thefuzzyorange** [comment]
Oh wow. That worked like a charm! =) Thank you so much! Looking forward to trying out this neat utility!

Suggestion to update the project page with the above for other people
