### ISSUE TITLE
Aero 15 UK layout?

### ISSUE THREAD

**Issue by aahern** [martin31821/fusion-kbd-controller#3]
Hi, doesn't seem to work on my Aero 15.
UK layout, but keyboard VID and PID are the same, doesn't give any errors.
Wondering if you have any idea how to adapt it for my machine?

Thanks

**Comment by guillaumesalagnac** [comment]
it does work with my French (aka "Azerty") keyboard

**Comment by martin31821** [comment]
I don't see why it shouldn't work with an UK layout, especially because you don't get any errors...

**Comment by aahern** [comment]
It is the Aero 15, not the Aero 15X but since the VID and PID are the same it's the same component right?
Do you have any advice for debugging to see what's going on?
Cheers

**Comment by martin31821** [comment]
You could use a Windows VM, passthrough the usb device of your keyboard and use the original gigabyte tool and wireshark to get some dumps of what's going on.

IMHO, if VID & PID match, it should work. What was the command line you tried?

**Comment by martin31821** [comment]
You could use a Windows VM, passthrough the usb device of your keyboard and use the original gigabyte tool and wireshark to get some dumps of what's going on.

IMHO, if VID & PID match, it should work. What was the command line you tried?

**Comment by aahern** [comment]
User error, thanks for the util it works great, so can confirm Aero 15 works. I had misunderstood the parameters.
